### ISSUE TITLE
More Info on Readme

### ISSUE THREAD

**Issue by aaronfrost** [parro-it/electron-detach#4]
I am trying to figure out how to use this. I have used it as I think I should, but I can't figure it out. Can you please give us a more comprehensive example on the readme? I have spend hours now trying to build this same thing, and can't. Please help me understand how to use your lib.

**Comment by parro-it** [comment]
Thank you for your interest. I'm not sure if you need more info on how to use the lib or on how it work internally.

Regarding the usage is really simple. You can seee it in action [here](https://github.com/parro-it/termite/blob/master/src/index.js) at bottom of file.
You simply call the function. If it return false it means it detects that the current process is running in a terminal. In this case, you have to avoid do other thinks, since the current process is actually quitting, and restarting as a [detached one](https://nodejs.org/api/child_process.html#child_process_options_detached).

If it return true, it means that we are not running in a terminal (either because you start the app from start menu or desktop, or because we are in the process already restarted as detached).

I hope to had given you some help, please ask for more if needed, I'm not a native english speaker so it's not easy for me to explain...

If you got other problem with the lib, try to explain them in more detail, I can provide other help.

**Comment by aaronfrost** [comment]
Here is a PR with the explanation you gave me. It was more clear than what was on the readme before. This is just a suggestion. Perhaps it may help someone else. 

Here is my PR. https://github.com/parro-it/electron-detach/pull/7

**Comment by aaronfrost** [comment]
The PR was merged. Closing.

**Comment by parro-it** [comment]
Could I ask you also some suggestion on how to rephrase the `api` sectio in order to improve it?

**Comment by aaronfrost** [comment]
Yeah. I just submitted a PR. Let me know.

**Comment by parro-it** [comment]
Thank you!T
